Addressing Warren's nits
rtcweb-wg/rtcweb-overview pull request #17
Opened 2017-05-11 14:06 UTC by seanturner

Made changes to address Warren's first and third, but not 2nd nit.  I'm unsure whether the changes in the spacing I introduced will fix the odd spacing in Olle's name.

Closes #16.

2017-05-11 21:56 UTC, fluffy requested changes

2017-05-11 21:56 UTC, fluffy commented on rtcweb-overview.xml
> +      <t>Development of The Universal Solution has proved, however, proved
seems like an extra proved here

2017-06-02 17:32 UTC, fluffy approved these changes

2017-06-04 01:04 UTC, martinthomson approved these changes

2017-06-04 01:04 UTC, martinthomson commented on rtcweb-overview.xml
> +      <t>Development of The Universal Solution has, however, proved hard.</t>
perjorative.

2017-06-04 05:58 UTC, seanturner commented on rtcweb-overview.xml
> +      <t>Development of The Universal Solution has, however, proved hard.</t>
It is, but it is also true :(

2017-10-19 18:04 UTC, merged